[package]
name = "chess_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess_engine = { path = "../chess_engine" }
macroquad = "0.3"
# web-sys = {version = "0.3.60", features = ["WebSocket"]}